spring.data.mongodb.uri = mongodb://localhost:27017/Url_db
app.allowed.origin = https://localhost:5173

spring.output.ansi.enabled=always


brevo.api.key=your_brevo_api_key_here
app.mail.from=your_email@example.com

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


logging.level.root=INFO
spring.data.mongodb.auto-index-creation=true
server.port=${PORT:8080}